name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # o la rama que uses para producción
  pull_request:
    branches:
      - main  # o la rama que uses para producción

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cambia según la versión que necesites

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: wzieba/Firebase-Distribution@v1
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TSS_1S2024 }}
          projectId: your-project-id  # Cambia esto por tu ID de proyecto
          token: ${{ secrets.FIREBASE_TOKEN }}  # Si usas token en lugar de cuenta de servicio
